apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: postgresdb
  name: postgresdb
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: postgresdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: postgresdb
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: matthias
        - name: POSTGRES_DB
          value: mydb
        image: postgres:latest
        imagePullPolicy: IfNotPresent
        name: postgresdb
